### ISSUE TITLE
Install instruction have wrong package name

### ISSUE THREAD

**Issue by SamuelSwartzberg** [derhuerst/url-parser-cli#9]
Install instructions in readme are

```
cargo install chunked_transfer_cli
```

but shouldn't that be

```
cargo install url_parser_cli
```

?

**Comment by derhuerst** [comment]
Yes, thanks for the hint! Do you want to send a PR?

**Comment by SamuelSwartzberg** [comment]
Eh, is it really worth it for such a minor README change? I don't need credit or anything, you have the repo cloned already, I'd say you just do it, no?
